### ISSUE TITLE
Merging documents of different kinds

### ISSUE THREAD

**Issue by lroal** [BitMiracle/Docotic.Pdf.Samples#1]
Hello.
I am a paying customer.
Are there any samples on how to merge different kind of documents to a single pdf ?
Typically a mix of png, tif, jpg, pdf to a multipage pdf.

**Comment by Bobrovsky** [comment]
Hello Lars-Erik,

The library can only [merge PDFs](https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/General%20operations/MergeDocuments). If you want to create a PDF from a set of images and PDFs, then please convert [images to PDF(s)](https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Images/AddAndDrawImage) first and then merge PDFs.
