### ISSUE TITLE
PdfPath to image

### ISSUE THREAD

**Issue by dayerqq** [BitMiracle/Docotic.Pdf.Samples#10]
How to convert PdfPath type to image. I want to get the PdfPath and then preview it

**Comment by shibaev** [comment]
Look at the [ExtractPageObjects](https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Pages%20and%20Navigation/ExtractPageObjects) sample. This sample shows how to process page objects with System.Drawing.Graphics. Paths are processed in the drawPath method.

Alternatively, you can draw your paths to a new PDF page and then save this page as image. Related samples:
1. [CopyPageObjects](https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Pages%20and%20Navigation/CopyPageObjects) - you can copy paths only.
2. [SavePageAsImage](https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Draw%20and%20print%20PDF/SavePageAsImage) - shows how to save PDF page as image.
