### ISSUE TITLE
I found that the Y-axis coordinates of the elements obtained using sourcePage.GetChars() and srcXObject.GetObjects(m_options) are different while using CopyPageObjects.

### ISSUE THREAD

**Issue by dayerqq** [BitMiracle/Docotic.Pdf.Samples#11]
While processing a document, I needed to remove a line of text, so I used the method inside CopyPageObjects to make the determination. However, I found it difficult to distinguish the text information that I needed to delete. This is because the content of the elements obtained using sourcePage.GetChars() is like this.
![image](https://github.com/BitMiracle/Docotic.Pdf.Samples/assets/45892245/2ac339e0-51ec-4b3f-b63a-4e81b42c9bd6)

But the content obtained using the method srcXObject.GetObjects(m_options) has different Y-axis coordinates:
![1698833217156](https://github.com/BitMiracle/Docotic.Pdf.Samples/assets/45892245/2e7322b1-3381-45ea-9be4-33782a5f28e5)

The Y-coordinate obtained from sourcePage.GetChars() is 198.1, while the Y-coordinate obtained from srcXObject.GetObjects(m_options) is 185.53.

[bug.pdf](https://github.com/BitMiracle/Docotic.Pdf.Samples/files/13225691/bug.pdf)

**Comment by shibaev** [comment]
You need to take into account `PdfTextData.TransformationMatrix` when comparing text data coordinates. The transformation matrix is not identity for text chunks related to XObject when extracted using `GetObjects({ FlattenXObects = false })`. And it is identity when extracted using `GetChars()` or `GetWords()`. The Y difference correspond to the difference between `TransformationMatrix.OffsetY` values.
