### ISSUE TITLE
Scan pdf not converting

### ISSUE THREAD

**Issue by urwithranjan** [BitMiracle/Docotic.Pdf.Samples#15]
Scan pdf file not extracting 

![image](https://github.com/BitMiracle/Docotic.Pdf.Samples/assets/2210056/0569b0a9-8072-4d19-b381-93bcd51ed908)

**Comment by shibaev** [comment]
You need to perform OCR to extract text from scanned PDF documents. Related code samples:
* https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Text/OcrAndExtractText
* https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Text/OcrAndMakeSearchable

Read the [OCR PDF in C# and VB.NET - how to extract text from non-searchable PDF](https://bitmiracle.com/blog/ocr-pdf-in-net) article for more detail.

**Comment by urwithranjan** [comment]
Thanks for sharing the details.

I tied both classes but am still getting the error


   -
   https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Text/OcrAndExtractText
   -
   https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Text/OcrAndMakeSearchable

*Error message*
Tesseract.TesseractException
  HResult=0x80131500
  Message=Failed to initialise tesseract engine.. See
https://github.com/charlesw/tesseract/wiki/Error-1 for details.
  Source=Tesseract
  StackTrace:
   at Tesseract.TesseractEngine.Initialise(String datapath, String
language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2
initialValues, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language,
EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2
initialOptions, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language,
EngineMode engineMode)
   at BitMiracle.Docotic.Pdf.Samples.OcrAndMakeSearchable.Main() in
C:\Application\invoice-extract\invoice.extract\invoice.extract\OcrAndMakeSearchable.cs:line
35
   at Program.<Main>$(String[] args) in
C:\Application\invoice-extract\invoice.extract\invoice.extract\Program.cs:line
11


*Thanks & Regards*

*Ranjan Kumar*

*Email: ***@***.*** ***@***.***>*

**Comment by shibaev** [comment]
It looks like you did not properly copy project configuration to your `invoice.extract` project. First, run our sample projects without any changes and make sure they work. Then, copy csproj/C# configuration to your project, make sure to restore all packages.

With the correct configuration, the output directory of your project must contain "tessdata", "x64", "x86" directories and Tesseract.Data.English.targets, Tesseract.dll files.
