### ISSUE TITLE
Questions about the use of the GetObjects method

### ISSUE THREAD

**Issue by howzew** [BitMiracle/Docotic.Pdf.Samples#16]
I use the latest 9.4 version, and through the following code to get the text in the PDF file：

`
using BitMiracle.Docotic.Pdf;
using System.Drawing;
using System.Management;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Data;

namespace WpfAppnet8
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void btn1_Click(object sender, RoutedEventArgs e)
        {
            List<string> pdft = new List<string>();

            using (var pdf = new BitMiracle.Docotic.Pdf.PdfDocument("test.pdf"))
            {
                var options = new PdfObjectExtractionOptions
                {
                    // Set this option to true if you need to convert searchable text to vector paths
                    ExtractTextAsPath = false,

                    // Set this option to true to ignore marked content (such as layers or tagged data)
                    //
                    // This sample does not preserve all structure information because page objects are
                    // copied to another page. Look at the EditPageContent sample that shows how to copy
                    // page objects to the same page and preserve all structure information.
                    FlattenMarkedContent = true,

                    // Usually, you need to set this option to false. That allows to properly handle
                    // documents with transparency groups.
                    // The value = true is recommended for backward compatibility or if you do not
                    // worry about transparency.
                    FlattenXObjects = true,
                };

                for (int i = 0; i < pdf.PageCount; i++)
                {
                    PdfPage page = pdf.Pages[i];

                    foreach (PdfPageObject obj in page.GetObjects(options))
                    {
                        if (obj.Type == PdfPageObjectType.Text)
                        {
                            PdfTextData text = (PdfTextData)obj;

                            pdft.Add(text.GetText());
                        }

                    }

                }

                MessageBox.Show("pdft.count is :" + pdft.Count);
            }

        }

    }

}
`

the strange phenomenon is: the first run, the prompt got 28582 words, but when I click the button again, the prompt only gets 221 words, that is, this code, the result of the first execution and the second execution is not the same, I tried to print each of the obtained texts, found the problem, I found that the second run, the pdf file from the second page can not get any text, I don't know if this is a bug or my way of using it is wrong.

Please see the attachment for the test pdf file, thank you

[test.pdf](https://github.com/user-attachments/files/16064929/test.pdf)

**Comment by shibaev** [comment]
It looks like this issue is already fixed. Try the version https://www.nuget.org/packages/BitMiracle.Docotic.Pdf/9.4.17423-dev. Does it work for you?

I reproduced the issue in WPF .NET 8 application with the version 9.4.17342 but not with 9.4.17423-dev.

**Comment by howzew** [comment]
Thank you,it fixed.
