### ISSUE TITLE
The order of extracting pictures is disordered

### ISSUE THREAD

**Issue by howzew** [BitMiracle/Docotic.Pdf.Samples#17]
When I use the pdf.GetImages() method to extract images from the test file, I find that the order of the extracted images is not arranged according to the order in the file. 

There is a mix-up, and there are a few extra images. What is the reason for this?

[test.pdf](https://github.com/user-attachments/files/17300574/test.pdf)

**Comment by Bobrovsky** [comment]
I checked the file and everything works as designed. 

1. According to [the docs](https://api.docotic.com/pdfdocument-getimages), the `GetImages` method returns: 
> .. the collection of document images **including** inline images and **images added to document but not yet drawn on any canvas.**

2. The order of the images in the result of the GetImages method is not defined. The library definitely does not try to maintain any order.

Usually, for an image-only PDF with one image per page, you will get images in the same order as the appear on pages. But there is no guarantee this will always be the case.

The actual order and the number of extracted images depend on the internal structure of the PDF with the images.

For this PDF, all images are referenced from the resource dictionary of the first page. All other pages reuse the same resource dictionary. Each page uses only some of the images referenced in the resource dictionary.

Not a single page uses images `/I3`, `/I13`, or `/I14`. This describes the "extra" images.

The order of references in the resource dictionary does not correspond to the order in which the images are displayed in the document. This describes the "mix-up".
