### ISSUE TITLE
Does Docotic.Pdf support creating image objects directly from raw pixel data？

### ISSUE THREAD

**Issue by howzew** [BitMiracle/Docotic.Pdf.Samples#18]
I try to use Docotic.Pdf in avalonia. In avalonia, the image uses the WriteableBitmap format. 

If I use the following code:

```
using Avalonia.Media.Imaging;
using System.IO;

public byte[] WriteableBitmapToByteArray(WriteableBitmap writeableBitmap)
{
    using (var memoryStream = new MemoryStream())
    {
        writeableBitmap.Save(memoryStream);
        return memoryStream.ToArray();
    }
}

var b = WriteableBitmapToByteArray(outbitmap);

PdfImage outimage = pdf.AddImage(b);
```

I can get the correct outimage, but if I use the following code：

```
using Avalonia.Media.Imaging;
using System;
using System.Runtime.InteropServices;

public byte[] WriteableBitmapToByteArray(WriteableBitmap writeableBitmap)
{
    using (var lockedBitmap = writeableBitmap.Lock())
    {
        int length = lockedBitmap.Size.Width * lockedBitmap.Size.Height * 4; // assuming 32bpp
        byte[] pixels = new byte[length];
        Marshal.Copy(lockedBitmap.Address, pixels, 0, length);
        return pixels;
    }
}

var b = WriteableBitmapToByteArray(outbitmap);

PdfImage outimage = pdf.AddImage(b);
```

the outimage I get is null. 

The second method only copies the original pixel data without metadata such as the image file header. Therefore, when it is passed to the pdf.AddImage method, the PDF library cannot recognize the data format, resulting in outimage being null. 

I find that iTextSharp 7 provides the ImageDataFactory.Create method, but I don't know if Docotic.Pdf has a similar method to solve this problem.

Thank you

**Comment by Bobrovsky** [comment]
Your question is unrelated to Docotic.Pdf.Samples. Please [contact support](https://bitmiracle.com/support) using the means listed on the official site.
