### ISSUE TITLE
Custom Action on clicking each PdfOutlineItem

### ISSUE THREAD

**Issue by krishnapsarthi** [BitMiracle/Docotic.Pdf.Samples#4]
Hi,

Using the library as a paid customer. We are using the library for generating bookmarks (outlines) in the pdf documents. We have a requirement to highlight the currently selected/clicked outline. I observed that we can assign a PdfAction to PdfOutlineItem.Action property. I tried JavascriptAction to change the style of selected outline, but that doesn't seems to be working. Do we need to create a custom PdfAction to get this working? Any suggestions.

**Comment by Bobrovsky** [comment]
You are moving in the right direction. To be able to update an outline item in a compatible viewer, you would need to attach some Javascript action to it. 

Please create a `PdfJavaScriptAction` using `PdfDocument.CreateJavaScriptAction` method and your script. And then attach the action to `PdfOutlineItem.Action` property. 

It is not clear what is not working in your case, so please feel free to provide us a code sample so we could try to help you.

**Comment by krishnapsarthi** [comment]
Hi, 

Thanks for quick response and sorry for late reply. Following summarizes my issue.

The JavascriptAction script need to change the style (either color or font bold/italic) of the PdfOutlineItem to which the PdfJavaScriptAction is attached to. But I am not able to get access to PdfOutlineItem object in the script. I tried to get reference first by `this` and find the PdfOutlineItem by its title, but that doesn't work.


```
using PdfDocument pdfDocument = new PdfDocument(pdfStream);

pdfDocument.PageMode = PdfPageMode.UseOutlines;
PdfOutlineItem root = pdfDocument.OutlineRoot;

PdfOutlineItem  pageOutline = root.AddChild(bookmarkModel.Title, bookmarkModel.Index);

string jsScript = $"this.getField('{bookmarkModel.Title}')";

pageOutline.Action = pdfDocument.CreateJavaScriptAction("app.alert(" + jsScript + ", 3)");
```
I get null from jsScript response.
How I can get access to pageOutline from within the script?

**Comment by shibaev** [comment]
You need to search in the doc.bookmarkRoot collection. Look at these sections:
- "Bookmarks" at page 125 in https://opensource.adobe.com/dc-acrobat-sdk-docs/acrobatsdk/pdfs/acrobatsdk_jsdevguide.pdf
- "Bookmark" at page 171 in https://opensource.adobe.com/dc-acrobat-sdk-docs/acrobatsdk/pdfs/acrobatsdk_jsapiref.pdf

**Comment by shibaev** [comment]
By the way, why do you need to manually highlight selected/clicked outline? PDF viewers (Adobe Reader/Acrobat, Foxit Reader, PDF-XChange Editor) already highlight selected outline. And if some PDF viewer does not support highlighting of outlines then unlikely it can execute Acrobat JavaScript.

**Comment by krishnapsarthi** [comment]
@shibaev thanks for sharing the links. It did helped me to get required information. Following sample script will get the work done partially for me

```
string jsScript = @"var root = this.bookmarkRoot.children;
                                               for (var i = 0; i < root.length; i++) {
                                                if (root[i].name =='" + bookmarkModel.Title + @"')
                                                {
                                                    root[i].style = 2;
                                                }else{
                                                    root[i].style = 0;
                                                }
                                            }";
pageOutline.Action = pdfDocument.CreateJavaScriptAction(jsScript);

```
However adding a JavascriptAction, removes the existing PdfGoToAction. The NextActions property is a read-only property and we can't add both these actions to same outline. I assume there would be some option to create a PdfAction with NextActions collection.

**Comment by shibaev** [comment]
Great that you got a working script! You can use `action.NextActions.Add(..)` method to assign a second action.
