### ISSUE TITLE
Large PDF with images, layers does not covert

### ISSUE THREAD

**Issue by fasteddys** [BitMiracle/Docotic.Pdf.Samples#5]
Hello I tried some larger PDF's with non text images I am facing issues where it hangs our exceptions. Is there a way to buffer the document and strip non-text images before OCR.

Also, is there a way to png/jpg load images _with txt_ as PDF and perform the ocr

**Comment by shibaev** [comment]
> Hello I tried some larger PDF's with non text images I am facing issues where it hangs our exceptions. Is there a way to buffer the document and strip non-text images before OCR.

Could you please provide more detail about your problem? I.e., sample PDF document, your code and exception details.

> Also, is there a way to png/jpg load images with txt as PDF and perform the ocr

Please clarify too. Do have an input image and want to generate a PDF document with this image and recognized text?

**Comment by fasteddys** [comment]
Let me clarify, I have PDF documents (which were flattened) since they had images and fairly large 200 pages, its having problems with size and embedded images inside the PDF

Secondly I was suggesting the same recognition on jpg images as PDF

**Comment by shibaev** [comment]
Please provide sample documents and code to reproduce and research problems you mention. You can upload large documents to Dropbox/Google Drive/OneDrive and share link to them. You can also send documents to support@bitmiracle.com if you do not want to share documents via GitHub.
