### ISSUE TITLE
How to sign the specified page or each page？

### ISSUE THREAD

**Issue by howzew** [BitMiracle/Docotic.Pdf.Samples#6]
It seems that the example only shows how to sign the entire file, and how to sign the specified page or each page?

**Comment by Bobrovsky** [comment]
The `SignDocument` sample shows how to sign document with an auto-added invisible signature field. The `SignSignatureField` shows how to sign specific signature field.

**Comment by howzew** [comment]
@Bobrovsky 
Thank you for your reply. 
If a PDF file has signature field on both the first and third pages, how can I sign both fields at once?
