### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by howzew** [BitMiracle/Docotic.Pdf.Samples#7]
1、How to sign multiple fields at once。
For example，If a PDF file has signature field on both the first and third pages, how can I sign both fields at once?
2、When copying a page using the "CopyPageObjects" method, the signature information will be lost.

**Comment by shibaev** [comment]
Signing of multiple fields is not supported at the moment. 

[EditPageContent sample](https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Pages%20and%20Navigation/EditPageContent) shows how to preserve page widgets (such as signature fields) when copying page objects.

# Update
Signing of multiple fields is supported since Docotic.Pdf 9.1. Related sample: [SignByMultiplePeople](https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Digital%20signatures/SignByMultiplePeople)

**Comment by howzew** [comment]
> Signing of multiple fields is not supported at the moment.
> 
> [EditPageContent sample](https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Pages%20and%20Navigation/EditPageContent) shows how to preserve page widgets (such as signature fields) when copying page objects.

I'm sorry, but in this example, it seems that there is no way to preserve page widgets

**Comment by shibaev** [comment]
Try to run this sample. It uses [form.pdf](https://github.com/BitMiracle/Docotic.Pdf.Samples/blob/master/Samples/Sample%20Data/form.pdf), which contains form fields. They are properly preserved.

You can also run the sample for the document with signature fields. E.g., [signed.pdf](https://github.com/BitMiracle/Docotic.Pdf.Samples/blob/master/Samples/Sample%20Data/signed.pdf). The signature field will be preserved too. If you want to re-sign the document then you need to use SignAndSave method with an appropriate certificate.

**Comment by howzew** [comment]
> Try to run this sample. It uses [form.pdf](https://github.com/BitMiracle/Docotic.Pdf.Samples/blob/master/Samples/Sample%20Data/form.pdf), which contains form fields. They are properly preserved.
> 
> You can also run the sample for the document with signature fields. E.g., [signed.pdf](https://github.com/BitMiracle/Docotic.Pdf.Samples/blob/master/Samples/Sample%20Data/signed.pdf). The signature field will be preserved too. If you want to re-sign the document then you need to use SignAndSave method with an appropriate certificate.

Thank you very much for your reply. I finally found out the reason. I always thought that using the "CopyPageObjects" example could retain the signature information in theory, but by comparing the "EditPageContent" example in detail, I found that in the "EditPageContent" example, after copying the original page to the temporary page, there was one more step, namely clearing the original page and copying the temporary page back to the original page. If there was no such step, The signature information of the original page cannot be retained (for example, the "CopyPageObjects" example).

**Comment by shibaev** [comment]
Yes, exactly.

**Comment by howzew** [comment]
> Yes, exactly.

But why can't the signature information be copied together when "CopyPageObjects" is used?

**Comment by shibaev** [comment]
It can - just modify the Main method in CopyPageObjects sample like EditPageContent. Or flatten signature field before copying.

PageObjectCopier class (from both samples) only copies objects drawn on a page. It does not copy annotation or controls. Signature field is a control so it is not copied by PageObjectCopier.

**Comment by howzew** [comment]
> It can - just modify the Main method in CopyPageObjects sample like EditPageContent. Or flatten signature field before copying.
> 
> PageObjectCopier class (from both samples) only copies objects drawn on a page. It does not copy annotation or controls. Signature field is a control so it is not copied by PageObjectCopier.

thank you very much
