### ISSUE TITLE
Is there a way to delete text directly from the page?

### ISSUE THREAD

**Issue by howzew** [BitMiracle/Docotic.Pdf.Samples#8]
I noticed that the example provides a method to directly delete images (RemovePaintedImages) and also provides a method to directly delete paths (RemovePaths), but I did not find a method to directly delete text. 

Why is this method not used? Is it specifically designed this way?

**Comment by shibaev** [comment]
Removing of text from PDF is much more trickier than removing of paths/images in general case. Thus, there is no separate method for that yet. [Edit PDF page content](https://github.com/BitMiracle/Docotic.Pdf.Samples/tree/master/Samples/Pages%20and%20Navigation/EditPageContent) sample is the only way to completely delete text from document at the moment.
